# Generated by Django 6.0.6 on 2026-06-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Heatwave', 'Heatwave'), ('Flood', 'Flood'), ('Cyclone', 'Cyclone'), ('Rainfall', 'Rainfall'), ('Drought', 'Drought')], max_length=16)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=16)),
                ('district', models.CharField(default='All districts', max_length=64)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimatePlayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('speed', models.IntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario_category', models.CharField(default='Custom', help_text='Scenario category name', max_length=32)),
                ('temp_change', models.FloatField(default=0.0, help_text='Temperature delta in Celsius')),
                ('rainfall_change', models.FloatField(default=0.0, help_text='Percentage rainfall change')),
                ('humidity_change', models.FloatField(default=0.0, help_text='Humidity delta in percentage points')),
                ('wind_change', models.FloatField(default=0.0, help_text='Wind delta in knots')),
                ('pressure_change', models.FloatField(default=0.0, help_text='Pressure delta in hPa')),
                ('sst_change', models.FloatField(default=0.0, help_text='SST delta in Celsius')),
                ('lst_change', models.FloatField(default=0.0, help_text='LST delta in Celsius')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rainfall_change', models.FloatField(help_text='Percentage rainfall change (-50 to +50)')),
                ('temperature_change', models.FloatField(help_text='Temperature delta in Celsius (-5 to +5)')),
                ('humidity_change', models.FloatField(help_text='Humidity delta in percentage points (-20 to +20)')),
                ('drought_risk', models.CharField(help_text='Low/Medium/High/Critical', max_length=16)),
                ('flood_risk', models.CharField(help_text='Low/Medium/High/Critical', max_length=16)),
                ('heatwave_risk', models.CharField(help_text='Low/Medium/High/Critical', max_length=16)),
                ('agricultural_impact', models.CharField(help_text='Risk status description', max_length=32)),
                ('water_stress_index', models.FloatField(help_text='Calculated stress coefficient (0.0 to 100.0)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimatePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('latitude', models.FloatField(default=15.9)),
                ('longitude', models.FloatField(default=79.7)),
                ('rainfall', models.FloatField(help_text='Predicted rainfall in mm')),
                ('temperature', models.FloatField(help_text='Predicted temperature in Celsius')),
                ('humidity', models.FloatField(default=60.0, help_text='Predicted humidity percentage')),
                ('pressure', models.FloatField(default=1008.0, help_text='Predicted atmospheric pressure in hPa')),
                ('wind', models.FloatField(default=10.0, help_text='Predicted wind speed in knots')),
                ('lst', models.FloatField(default=35.0, help_text='Predicted Land Surface Temp in Celsius')),
                ('sst', models.FloatField(default=0.0, help_text='Predicted Sea Surface Temp in Celsius')),
                ('prediction_confidence', models.FloatField(default=0.85, help_text='Model prediction confidence score (0.0 to 1.0)')),
                ('horizon', models.CharField(default='1-day', help_text='Forecast horizon: 1-day, 3-day, 7-day', max_length=16)),
                ('rainfall_prediction', models.FloatField(default=0.0, help_text='Predicted rainfall in mm')),
                ('temperature_prediction', models.FloatField(default=0.0, help_text='Predicted temperature in Celsius')),
                ('humidity_prediction', models.FloatField(default=60.0, help_text='Predicted humidity percentage')),
                ('wind_speed_prediction', models.FloatField(default=10.0, help_text='Predicted wind speed in knots')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='climate_twin.district')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ClimateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('temperature', models.FloatField(help_text='Air temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Relative humidity percentage')),
                ('pressure', models.FloatField(default=1008.0, help_text='Atmospheric pressure in hPa')),
                ('wind', models.FloatField(default=14.0, help_text='Wind speed in knots')),
                ('lst', models.FloatField(help_text='Land Surface Temperature in Celsius')),
                ('sst', models.FloatField(help_text='Sea Surface Temperature in Celsius')),
                ('wind_speed', models.FloatField(default=0.0, help_text='Wind speed in knots (alias)')),
                ('wind_direction', models.CharField(default='N', help_text='Wind direction vector', max_length=8)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='climate_twin.district')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heatwave_risk', models.CharField(help_text='Low/Medium/High/Critical', max_length=16)),
                ('flood_risk', models.CharField(help_text='Low/Medium/High/Critical', max_length=16)),
                ('drought_risk', models.CharField(help_text='Low/Medium/High/Critical', max_length=16)),
                ('cyclone_risk', models.CharField(help_text='Low/Medium/High/Critical', max_length=16)),
                ('agriculture_risk', models.CharField(help_text='Low/Medium/High/Critical', max_length=16)),
                ('water_stress', models.FloatField(help_text='Falkenmark index or calculated stress index (0.0 to 100.0)')),
                ('crop_stress', models.FloatField(help_text='Calculated crop stress (0.0 to 100.0)')),
                ('attribution_insights', models.JSONField(default=dict, help_text='Feature importance and insight attribution from models')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='climate_twin.district')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='climate_twin.climateobservation')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='climate_twin.climateprediction')),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='climate_twin.climatesimulation')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='climate_twin.state'),
        ),
        migrations.AddIndex(
            model_name='climateobservation',
            index=models.Index(fields=['latitude', 'longitude'], name='climate_twi_latitud_85f5d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'state')},
        ),
    ]
