# Generated by Django 6.0 on 2026-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_twin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateobservation',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climateobservation',
            name='day_of_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climateobservation',
            name='is_ocean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='climateobservation',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climateobservation',
            name='wind_u',
            field=models.FloatField(blank=True, help_text='Calculated U vector', null=True),
        ),
        migrations.AddField(
            model_name='climateobservation',
            name='wind_v',
            field=models.FloatField(blank=True, help_text='Calculated V vector', null=True),
        ),
        migrations.AddField(
            model_name='climateobservation',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climateobservation',
            name='sst',
            field=models.FloatField(blank=True, help_text='Sea Surface Temperature in Celsius', null=True),
        ),
    ]
